### ISSUE TITLE
Wrong package installed due to capitalisation of name

### ISSUE THREAD

**Issue by lucasnetau** [hiqdev/asset-packagist#123]
I am attempting to install npm-asset/formBuilder (https://www.npmjs.com/package/formBuilder) however this is getting installed as npm-asset/formbuilder (https://www.npmjs.com/package/formbuilder) which is not the library I am attempting to install.

If you search on https://asset-packagist.org/package/search?query=formBuilder&platform=bower%2Cnpm you will get the correct npm package coming up in the search results, but clicking through takes you to the lowercase version.

How can the correct library be installed?

**Comment by stof** [comment]
Composer treats package names as case insensitive. so having 2 package names differing only by the case is not supported.

**Comment by hiqsol** [comment]
Sorry, this issue will not be fixed in this repository.

But you just don't need asset-packagist to get the package cause it is available through the main packagist:

https://github.com/kevinchappell/formBuilder/blob/master/composer.json
https://packagist.org/packages/kevinchappell/form-builder

And actually that's the recommended way for all corner cases :) Add the package to packagist.
